### PR TITLE
Add single-command mode

### LINKED ISSUE #4: Fallback from Interactive Mode
Hi,

I'm encountering an issue where my environment isn't captured due to a zsh plugin I'm running. I run the [tmux plugin](https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins#tmux) for [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh/) with the `ZSH_TMUX_AUTOSTART` option turned on, which means that when `/bin/zsh -i` is run, it opens up tmux and causes issues for non-interactive processes opening it up expecting a prompt but getting a tmux instead. I've encountered this issue with my text editor also, but was able to configure my text editor not to use interactive mode, which works for me because I only start up tmux automatically in interactive mode.

I understand that in practice, people are likely to set their environments in their `.zshrc`, so simply turning off interactive mode would not be an acceptable solution in this case. I'm wondering if you'd be open to a PR which detects whether or not the appropriate environment from running interactive mode, and if not, running non-interactive mode to see if it can gather more environment?

### PR DESCRIPTION
**Pull request by hughrawlinson**
In an attempt to fix #4.

### CODE REVIEW

**Comment by silverwind** [comment]
This won't work for `fish`:

```
$ fish -tilp "env;exit"
fish: invalid option -- 't'
```

On the upside, `bash`, `zsh`, `ksh` and `tcsh` support the argument. We also might be able to drop the `exit` command.

**Comment by sindresorhus** [comment]
> We also might be able to drop the exit command.

Isn't the `exit` command good to have just in case something block it from exiting? We have no idea what kind of dumb stuff people put in their dotfiles.

**Comment by silverwind** [comment]
> Isn't the exit command good to have just in case something block it from exiting? We have no idea what kind of dumb stuff people put in their dotfiles.

I don't think that `exit` will protect us from such things, but I noticed that when ommitting the exit while in the REPL, it drops me straight out of it for some weird reason:

```
> require(".")()
Promise { <pending> }
> [6]  + 11363 suspended (tty input)  node
```

That doesn't happen with `exit` in place.

**Comment by sindresorhus** [comment]
@hughrawlinson Can you update to not add `t` when in `fish`?

**Comment by hughrawlinson** [comment]
Yep, I'll push a commit later today 😄

**Comment by hughrawlinson** [comment]
Well, that didn't go as expected, it is now bedtime. Sorry! I'll get to it ASAP.

**Comment by silverwind** [comment]
Before merging this, I'd make sure that all shells we supply `-t` to actually work as expected and execute only the given command. It's not totally clear to me why a command in a shell startup file shouldn't get picked as the chosen command because technically, it would be encountered earlier than the user-supplied command.

**Comment by sindresorhus** [comment]
ping :)

**Pull request closed without merging**
